/*
 * Copyright Telrock Communications Limited 2008 * 
 *
 * $Header:  $
 * $Revision:  $
 * $Date:  $ 
 * 
 */
package com.telrock.model;

public class Department
{
	//@formatter:off
	/*
	 * long id     - primary key, autogenerated
	 * String name - department's name
	 * String area - what is the department's area. Some departments may be in the same area.
	 */
	//@formatter:on
}
